version: "2.4"

services:

  app: &app
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:8000"
      - "-k"
      - "geventwebsocket.gunicorn.workers.GeventWebSocketWorker"
      - "-w"
      - "1"
      - "wsgi:app"
      - "--reload"
    volumes:
      - ./app:/code
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    <<: *app
    container_name: worker
    command:
      - "celery"
      - "--app"
      - "app.celery"
      - "worker"
      - "--loglevel=info"
    ports: []

  scheduler:
    <<: *app
    container_name: scheduler
    command:
      - "celery"
      - "--app"
      - "app.celery"
      - "beat"
      - "--loglevel=info"
    ports: []


  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    container_name: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
      - "8085:8081"
    depends_on:
      - "redis"

volumes:
  redis-data: