version: "2.4"

services:

  app: &app
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:8000"
      - "-k"
      - "geventwebsocket.gunicorn.workers.GeventWebSocketWorker"
      - "-w"
      - "1"
      - "wsgi:app"
      - "--reload"
    volumes:
      - ./app:/code
    environment:
      - REDIS_HOST=redis
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    <<: *app
    container_name: worker
    command:
      - "celery"
      - "--app"
      - "app.celery"
      - "worker"
      - "--loglevel=info"
    ports: []

  scheduler:
    <<: *app
    container_name: scheduler
    command:
      - "celery"
      - "--app"
      - "app.celery"
      - "beat"
      - "--loglevel=info"
    ports: []


  redis:
    image: redis/redis-stack:latest
    volumes:
      - redis-data1:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  redis-data1: