version: "2.4"

services:

  redis:
    image: redis/redis-stack:latest
    volumes:
      - redis-data1:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis

volumes:
  redis-data1: